apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  # namespace: text2sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      automountServiceAccountToken: false  # Disable service account token mounting if not needed
      containers:
      - name: model
        image: jieshilyn/ollama-llama-8b:latest
        ports:
          - containerPort: 11434
        resources:
          requests:
            # memory: "512Mi"      # Adjust according to the model's expected usage
            # cpu: "250m"          # Adjust according to the model's expected usage
            ephemeral-storage: "20Gi"  # Request for ephemeral storage
          limits:
            # memory: "1Gi"        # Adjust according to the model's expected usage
            # cpu: "9000m"          # Adjust according to the model's expected usage
            ephemeral-storage: "80Gi"  # Limit for ephemeral storage
