apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  namespace: text2sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - name: model
        image: jieshilyn/ollama-llama-8b
        ports:
          - containerPort: 11434
