apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: text2sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      imagePullSecrets:
      - name: my-dockerhub-secret
      # automountServiceAccountToken: false  # Disable service account token mounting if not needed
      securityContext:
        runAsUser: 1000950000    # Specify a non-root user if needed
        fsGroup: 1000950000  
      containers:
      - name: postgres
        image: jieshilyn/postgres-populated:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "pass"
        - name: POSTGRES_DB
          value: "chinook"
        resources:
          requests:
            # memory: "256Mi"
            # cpu: "250m"
            ephemeral-storage: "1Gi"  # Request for ephemeral storage
          limits:
            # memory: "512Mi"
            # cpu: "9000m"
            ephemeral-storage: "10Gi"  # Request for ephemeral storage
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
