apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbeaver
  namespace: text2sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbeaver
  template:
    metadata:
      labels:
        app: dbeaver
    spec:
      automountServiceAccountToken: false
      containers:
        - name: dbeaver
          image: dbeaver/cloudbeaver:latest
          env:
            - name: DBEAVER_HOME
              value: "/opt/dbeaver"
          ports:
            - containerPort: 8978
          resources:
            requests:
              # memory: "256Mi"
              # cpu: "250m"
              ephemeral-storage: "500Mi"
            limits:
              # memory: "512Mi"
              # cpu: "500m"
              ephemeral-storage: "5Gi"
          volumeMounts:
            - name: dbeaver-data
              mountPath: /root/.dbeaver4
      volumes:
        - name: dbeaver-data
          persistentVolumeClaim:
            claimName: dbeaver-pvc
