apiVersion: apps/v1
kind: Deployment
metadata:
  name: birds-stream-3
  namespace: text2sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: birds-stream-3
  template:
    metadata:
      labels:
        app: birds-stream-3
    spec:
      containers:
        - name: birds-stream-3
          image: quay.io/jeslynlamxy/birds_pg_generator:latest
          env:
            - name: FARM
              value: "Farm3"
            - name: TABLE
              value: "bird_locations"
            - name: PG_HOST
              value: "postgres"
            - name: PG_PORT
              value: "5432"
            - name: PG_DATABASE
              value: "chinook"
            - name: PG_USER
              value: "user"
            - name: PG_PASSWORD
              value: "pass"
            - name: DELAY_RANGE
              value: "0.1-1"
          resources:
            requests:
              # memory: "128Mi"
              # cpu: "100m"
              ephemeral-storage: "250Mi"
            limits:
              # memory: "256Mi"
              # cpu: "200m"
              ephemeral-storage: "500Mi"
